// Stock list: 1010 equities from stock-list-1000.json + 17 indices + comprehensive option underlyings
import stockData from "./stock-list-1000.json";

export const stockList = {
  equities: stockData.equities,
  indices: [
    { s: "NIFTY", n: "NIFTY 50", sec: "Index", bp: 24580, v: 0.012, ls: 25 },
    { s: "BANKNIFTY", n: "NIFTY BANK", sec: "Index", bp: 52800, v: 0.015, ls: 15 },
    { s: "NIFTYIT", n: "NIFTY IT", sec: "Index", bp: 38500, v: 0.016, ls: 50 },
    { s: "NIFTYNXT50", n: "NIFTY NEXT 50", sec: "Index", bp: 62450, v: 0.014, ls: 25 },
    { s: "NIFTYFIN", n: "NIFTY FIN SVC", sec: "Index", bp: 24300, v: 0.014, ls: 25 },
    { s: "NIFTYMIDCAP", n: "NIFTY MIDCAP 100", sec: "Index", bp: 58200, v: 0.015, ls: 50 },
    { s: "NIFTYSMLCAP", n: "NIFTY SMLCAP 100", sec: "Index", bp: 18400, v: 0.016, ls: 50 },
    { s: "NIFTYPHARMA", n: "NIFTY PHARMA", sec: "Index", bp: 19700, v: 0.015, ls: 50 },
    { s: "NIFTYAUTO", n: "NIFTY AUTO", sec: "Index", bp: 23200, v: 0.016, ls: 50 },
    { s: "NIFTYMETAL", n: "NIFTY METAL", sec: "Index", bp: 9850, v: 0.018, ls: 50 },
    { s: "NIFTYENERGY", n: "NIFTY ENERGY", sec: "Index", bp: 32500, v: 0.016, ls: 50 },
    { s: "NIFTYFMCG", n: "NIFTY FMCG", sec: "Index", bp: 57800, v: 0.011, ls: 50 },
    { s: "NIFTYREALTY", n: "NIFTY REALTY", sec: "Index", bp: 920, v: 0.02, ls: 50 },
    { s: "NIFTYINFRA", n: "NIFTY INFRA", sec: "Index", bp: 7850, v: 0.015, ls: 50 },
    { s: "NIFTYPSUBANK", n: "NIFTY PSE BANK", sec: "Index", bp: 6150, v: 0.018, ls: 50 },
    { s: "NIFTYCOMMOD", n: "NIFTY COMMODITY", sec: "Index", bp: 12500, v: 0.016, ls: 50 },
    { s: "INDIAVIX", n: "INDIA VIX", sec: "Index", bp: 14.5, v: 0.04, ls: 1 },
  ],
  optionUnderlyings: [
    "NIFTY", "BANKNIFTY", "FINNIFTY", "NIFTYIT", "NIFTYNXT50",
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "SBIN", "BHARTIARTL",
    "ITC", "HINDUNILVR", "LT", "KOTAKBANK", "AXISBANK", "ASIANPAINT",
    "BAJFINANCE", "MARUTI", "TITAN", "SUNPHARMA", "TATAMOTORS", "WIPRO",
    "HCLTECH", "ULTRACEMCO", "NESTLEIND", "NTPC", "POWERGRID", "ONGC",
    "TATASTEEL", "JSWSTEEL", "HINDALCO", "COALINDIA", "ADANIENT",
    "ADANIPORTS", "TECHM", "BAJAJFINSV", "DRREDDY", "CIPLA", "EICHERMOT",
    "M&M", "HEROMOTOCO", "BPCL", "GRASIM", "INDUSINDBK", "HDFCLIFE",
    "SBILIFE", "DIVISLAB", "DLF", "ADANIGREEN", "TATACONSUM", "BRITANNIA",
    "PIDILITIND", "APOLLOHOSP", "BERGEPAINT", "TRENT", "TATAPOWER",
    "TORNTPHARM", "TVSMOTOR", "VEDL", "VOLTAS", "ZYDUSLIFE", "PNB",
    "BANKBARODA", "CANBK", "UNIONBANK", "INDIANB", "FEDERALBNK",
    "BANDHANBNK", "IDFCFIRSTB", "AUBANK", "RBLBANK", "ICICIPRULI",
    "LICHSGFIN", "SHRIRAMFIN", "RECLTD", "PNBHOUSING", "MUTHOOTFIN",
    "CDSL", "LTIM", "PERSISTENT", "COFORGE", "TATAELXSI", "OFSS",
    "NAUKRI", "LUPIN", "LAURUSLABS", "SYNGENE", "WOCKPHARMA", "ALKEM",
    "AUROPHARMA", "AMARAJABAT", "APOLLOTYRE", "ASHOKLEY", "BOSCHLTD",
    "CEATLTD", "ESCORTS", "EXIDEIND", "NATIONALUM", "NMDC", "HINDZINC",
    "HINDPETRO", "GAIL", "IOC", "PETRONET", "JSWENERGY", "ADANIPOWER",
    "IGL", "SUZLON", "ACC", "AMBUJACEM", "RAMCOCEM", "SIEMENS", "ABB",
    "CGPOWER", "CUMMINSIND", "KEI", "POLYCAB", "HAVELLS", "DIXON",
    "GODREJPROP", "OBEROIRLTY", "PHOENIXLTD", "NBCC", "NCC", "IRCTC",
    "IRFC", "RVNL", "CONCOR", "RITES", "VODAIDEA", "YESBANK", "COLPAL",
    "GODREJCP", "MCDOWELL-N", "UBL", "VBL", "JUBLFOOD", "PAGEIND",
    "BATAINDIA", "WHIRLPOOL", "SUNTV", "JIOFIN", "DELHIVERY", "ZOMATO",
    "TATAINVEST", "BEL", "HAL", "ADANITRANS", "BIOCON", "DABUR", "PEL",
    "TATACHEM", "IDEA", "BALRAMCHIN", "MANAPPURAM", "EQUITASBNK",
    "FIVESTAR", "CHALET", "MEDPLUS", "SAREGAMA", "HAPPSTMNDS",
    "SCHAEFFLER", "MPHASIS"
  ]
} as const;
